// Auto-generated from database export
// Generated at: 2025-12-09T14:24:53.467Z

import { Prisma, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const decksData = [
  {
    id: 'cmio6dpsd00029apfrghrzjz1',
    name: 'KANJI N5',
    description: '',
    category: 'Kanji',
    difficulty: 'N5',
    isPublic: true,
    totalCards: 103,
    creatorEmail: 'ajib18j@gmail.com',
    flashcards: [
      {
        id: 'cmio6dpss00039apfvti5vfxk',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '一',
        kanjiMeaning: 'satu; radikal satu (no.1)',
        onyomi: 'イチ',
        kunyomi: 'ひと～、ひと・つ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '一つ[ひとつ], 一人[ひとり], 一番[いちばん], 一月[いちがつ]',
        exampleTranslation:
          'satu (penghitung umum), satu orang, pertama | terbaik; paling, Januari',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 0,
      },
      {
        id: 'cmio6dpss00049apf5pnidomi',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '七',
        kanjiMeaning: 'tujuh',
        onyomi: 'シチ',
        kunyomi: 'なな、なな・つ、なの',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '七つ[ななつ], 七日[なのか]',
        exampleTranslation: 'tujuh (penghitung umum), hari ketujuh dalam sebulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 1,
      },
      {
        id: 'cmio6dpss00059apfsm1fxrbx',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '万',
        kanjiMeaning: '10.000; sepuluh ribu',
        onyomi: 'マン',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '十万円[じゅうまんえん]',
        exampleTranslation: '100.000 yen',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 2,
      },
      {
        id: 'cmio6dpss00069apfq6mhgu83',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '三',
        kanjiMeaning: 'tiga',
        onyomi: 'サン',
        kunyomi: 'みっ・つ、み・つ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '三つ[みっつ], 三日[みっか]',
        exampleTranslation: 'tiga (penghitung umum), hari ketiga dalam sebulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 3,
      },
      {
        id: 'cmio6dpss00079apft8454soh',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '上',
        kanjiMeaning: 'atas; di atas',
        onyomi: 'ショウ、ジョウ',
        kunyomi: 'あ・がる、あ・げる、うえ、うわ～',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '上[あ]げる, 上手[じょうず], 上着[うわぎ]',
        exampleTranslation:
          'menaikkan; meninggikan | meningkatkan (harga, kualitas, status, dll.), terampil; mahir; pandai (dalam), mantel; jaket; pakaian luar',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 4,
      },
      {
        id: 'cmio6dpss00089apf4cm8yqab',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '下',
        kanjiMeaning: 'bawah; turun; rendah; inferior',
        onyomi: 'カ、ゲ',
        kunyomi: 'さ・がる、さ・げる、した、くだ・さる',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '下[した], 地下鉄[ちかてつ], 廊下[ろうか], 靴下[くつした], 下手[へた]',
        exampleTranslation:
          'bawah; di bawah, kereta bawah tanah, koridor; lorong, kaus kaki, tidak terampil; buruk; canggung',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 5,
      },
      {
        id: 'cmio6dpst00099apfzromxciz',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '中',
        kanjiMeaning: 'tengah; di; dalam; pertengahan',
        onyomi: 'チュウ',
        kunyomi: 'うち、なか',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '中国[ちゅうごく]',
        exampleTranslation: 'China',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 6,
      },
      {
        id: 'cmio6dpst000a9apfshkw1alt',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '九',
        kanjiMeaning: 'sembilan',
        onyomi: 'キュウ、ク',
        kunyomi: 'ここの、ここの・つ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '九つ[ここのつ], 九日[ここのか]',
        exampleTranslation: 'sembilan (penghitung umum), hari kesembilan dalam sebulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 7,
      },
      {
        id: 'cmio6dpst000b9apfivg3zu5u',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '二',
        kanjiMeaning: 'dua; radikal dua (no. 7)',
        onyomi: 'ニ',
        kunyomi: 'ふた・つ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '二つ[ふたつ], 二人[ふたり], 二日[ふつか]',
        exampleTranslation: 'dua (penghitung umum), dua orang; pasangan, hari kedua dalam sebulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 8,
      },
      {
        id: 'cmio6dpst000c9apfs0k8x10g',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '五',
        kanjiMeaning: 'lima',
        onyomi: 'ゴ',
        kunyomi: 'いつ、いつ・つ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '五つ[いつつ], 五日[いつか]',
        exampleTranslation: 'lima (penghitung umum), hari kelima dalam sebulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 9,
      },
      {
        id: 'cmio6dpst000d9apf4w0wcj3v',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '人',
        kanjiMeaning: 'orang',
        onyomi: 'ジン、ニン',
        kunyomi: '～と、～り、ひと',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence:
          '人[ひと], 一人[ひとり], 二人[ふたり], 外国人[がいこくじん], ご主人[しゅじん]',
        exampleTranslation:
          'orang, satu orang, dua orang; pasangan, orang asing; warga negara asing, (hormat) suami Anda',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 10,
      },
      {
        id: 'cmio6dpst000e9apf6se4pp99',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '今',
        kanjiMeaning: 'sekarang',
        onyomi: 'コン',
        kunyomi: 'いま',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '今年[ことし], 今晩[こんばん], 今月[こんげつ], 今週[こんしゅう]',
        exampleTranslation: 'tahun ini, malam ini, bulan ini, minggu ini',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 11,
      },
      {
        id: 'cmio6dpst000f9apfcvg96t14',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '休',
        kanjiMeaning: 'hari libur; istirahat; pensiun',
        onyomi: 'キュウ',
        kunyomi: 'やす・む',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '休[やす]み, 休[やす]む, 夏休[なつやす]み',
        exampleTranslation:
          'istirahat | liburan, mengambil cuti | beristirahat; istirahat sejenak, liburan musim panas',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 12,
      },
      {
        id: 'cmio6dpst000g9apfzbcnamtg',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '会',
        kanjiMeaning: 'asosiasi; bergabung; bertemu; pertemuan',
        onyomi: 'カイ',
        kunyomi: 'あ・う',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '会[あ]う, 会社[かいしゃ]',
        exampleTranslation: 'bertemu, perusahaan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 13,
      },
      {
        id: 'cmio6dpst000h9apfy3t91k65',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '何',
        kanjiMeaning: 'apa',
        onyomi: 'カ',
        kunyomi: 'なに、なん',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '何[なん]の料理[りょうり]',
        exampleTranslation: 'makanan jenis apa',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 14,
      },
      {
        id: 'cmio6dpst000i9apfvkakcdoj',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '先',
        kanjiMeaning: 'ke depan; sebelum; masa depan; sebelumnya',
        onyomi: 'セン',
        kunyomi: 'さき',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '先月[せんげつ], 先生[せんせい], 先週[せんしゅう]',
        exampleTranslation: 'bulan lalu, guru; dokter, minggu lalu',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 15,
      },
      {
        id: 'cmio6dpst000j9apf2htx5ux3',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '入',
        kanjiMeaning: 'masuk; memasukkan',
        onyomi: 'ニュウ',
        kunyomi: 'い・る、い・れる、はい・る',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '入[い]れる, 入[はい]る, 入口[いりぐち]',
        exampleTranslation:
          'memasukkan; menyisipkan, masuk; memasuki | bergabung; mendaftar, pintu masuk; entri',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 16,
      },
      {
        id: 'cmio6dpst000k9apfio8s4pm4',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '八',
        kanjiMeaning: 'delapan; radikal delapan (no. 12)',
        onyomi: 'ハチ',
        kunyomi: 'や、やっ・つ、や・つ、よう',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '八つ[やっつ], 八日[ようか], 八百屋[やおや]',
        exampleTranslation: 'delapan (penghitung umum), hari kedelapan dalam sebulan, tukang sayur',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 17,
      },
      {
        id: 'cmio6dpst000l9apftitmlj76',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '六',
        kanjiMeaning: 'enam',
        onyomi: 'ロク',
        kunyomi: 'む、むい、むっ・つ、む・つ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '六つ[むっつ], 六日[むいか]',
        exampleTranslation: 'enam (penghitung umum), hari keenam dalam sebulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 18,
      },
      {
        id: 'cmio6dpst000m9apfr4kv393t',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '円',
        kanjiMeaning: 'lingkaran; bulat; yen',
        onyomi: 'エン',
        kunyomi: 'まる・い',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '出[だ]す, 出[で]かける, 出[で]る, 出口[でぐち], 出来[でき]る',
        exampleTranslation:
          'mengeluarkan; mengambil keluar | menyerahkan (mis. tesis) | mengirim (mis. surat), pergi keluar (mis. jalan-jalan); berangkat, pergi; keluar; meninggalkan, pintu keluar, bisa melakukan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 19,
      },
      {
        id: 'cmio6dpst000n9apf8lsst0sl',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '出',
        kanjiMeaning: 'keluar; exit; pergi keluar; meninggalkan; menonjol; mengeluarkan',
        onyomi: 'シュツ',
        kunyomi: 'だ・す、で・る',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '分[わ]かる, 半分[はんぶん], 多分[たぶん], 自分[じぶん], ～分[ぶん]',
        exampleTranslation:
          'mengerti; memahami, setengah, mungkin; barangkali, diri sendiri, menit (satuan waktu) | penghitung untuk menit',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 20,
      },
      {
        id: 'cmio6dpst000o9apfu4re5ebx',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '分',
        kanjiMeaning: 'derajat; tahu; mengerti; menit waktu; bagian',
        onyomi: 'フン、ブン',
        kunyomi: 'わ・かる、わ・かれる、わ・ける',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '午前[ごぜん], 午後[ごご]',
        exampleTranslation: 'pagi; a.m., siang; p.m.',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 21,
      },
      {
        id: 'cmio6dpst000p9apfzsshy45j',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '前',
        kanjiMeaning: 'sebelum; di depan',
        onyomi: 'ゼン',
        kunyomi: 'まえ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '名前[なまえ],',
        exampleTranslation: 'nama | nama depan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 22,
      },
      {
        id: 'cmio6dpst000q9apfyk36fy56',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '北',
        kanjiMeaning: 'utara',
        onyomi: 'ホク',
        kunyomi: 'きた',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '北[きた]',
        exampleTranslation: 'utara',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 23,
      },
      {
        id: 'cmio6dpst000r9apf53r4xaic',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '十',
        kanjiMeaning: 'sepuluh',
        onyomi: 'ジュウ、ジュッ',
        kunyomi: 'とお',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '十万[じゅうまん], 十円[じゅうえん], 十個[じゅっこ], 十日[とおか]',
        exampleTranslation: '100.000, 10 yen, 10 objek kecil, hari kesepuluh dalam sebulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 24,
      },
      {
        id: 'cmio6dpst000s9apfaljh3bby',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '千',
        kanjiMeaning: 'seribu',
        onyomi: 'セン',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '千[せん]',
        exampleTranslation: 'seribu',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 25,
      },
      {
        id: 'cmio6dpst000t9apfbyiehzva',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '午',
        kanjiMeaning: 'tengah hari; tanda zodiak Cina ketujuh; tanda kuda',
        onyomi: 'ゴ',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '午前[ごぜん], 午後[ごご]',
        exampleTranslation: 'pagi; a.m., siang; p.m.',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 26,
      },
      {
        id: 'cmio6dpst000u9apf8xa13jl6',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '半',
        kanjiMeaning: 'setengah; tengah; bilangan ganjil; sebagian; semi-',
        onyomi: 'ハン',
        kunyomi: 'なか・ば',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '半[なか]ば',
        exampleTranslation: 'pertengahan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 27,
      },
      {
        id: 'cmio6dpst000v9apfsvidzfcw',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '南',
        kanjiMeaning: 'selatan',
        onyomi: 'ナン',
        kunyomi: 'みなみ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '南[みなみ]',
        exampleTranslation: 'selatan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 28,
      },
      {
        id: 'cmio6dpst000w9apfq4ls06v9',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '友',
        kanjiMeaning: 'teman',
        onyomi: 'ユウ',
        kunyomi: 'とも',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '友達[ともだち]',
        exampleTranslation: 'teman; sahabat',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 29,
      },
      {
        id: 'cmio6dpst000x9apf36dpne7u',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '口',
        kanjiMeaning: 'mulut',
        onyomi: 'ク、コウ',
        kunyomi: 'くち',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '口[くち], 入口[いりぐち], 出口[でぐち]',
        exampleTranslation: 'mulut, pintu masuk; entri, pintu keluar',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 30,
      },
      {
        id: 'cmio6dpst000y9apfq1rtp593',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '古',
        kanjiMeaning: 'tua',
        onyomi: 'コ',
        kunyomi: 'ふる・い',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '古[ふる]い',
        exampleTranslation: 'tua (bukan orang); lama; basi',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 31,
      },
      {
        id: 'cmio6dpst000z9apf3r6bxufn',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '右',
        kanjiMeaning: 'kanan',
        onyomi: 'ウ、ユウ',
        kunyomi: 'みぎ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '右[みぎ]',
        exampleTranslation: 'kanan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 32,
      },
      {
        id: 'cmio6dpst00109apfgtv8c0ou',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '名',
        kanjiMeaning: 'terkemuka; nama',
        onyomi: 'ミョウ、メイ',
        kunyomi: 'な',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '有名[ゆうめい]',
        exampleTranslation: 'terkenal',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 33,
      },
      {
        id: 'cmio6dpst00119apf84dofr92',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '四',
        kanjiMeaning: 'empat',
        onyomi: 'シ',
        kunyomi: 'よん、よっ・つ、よ・つ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '四つ[よっつ], 四日[よっか]',
        exampleTranslation: 'empat (penghitung umum), hari keempat dalam sebulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 34,
      },
      {
        id: 'cmio6dpst00129apfsrhhjrb3',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '国',
        kanjiMeaning: 'negara',
        onyomi: 'コク',
        kunyomi: 'くに',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '外国[がいこく], 外国人[がいこくじん]',
        exampleTranslation: 'negara asing, orang asing; warga negara asing',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 35,
      },
      {
        id: 'cmio6dpst00139apflqf5we6d',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '土',
        kanjiMeaning: 'tanah; permukaan; lapisan tanah',
        onyomi: 'ト、ド',
        kunyomi: 'つち',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '土曜日[どようび]',
        exampleTranslation: 'Sabtu',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 36,
      },
      {
        id: 'cmio6dpst00149apfv5n3hmjf',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '外',
        kanjiMeaning: 'luar',
        onyomi: 'ガイ',
        kunyomi: 'そと、はず・す、はず・れる、ほか',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '外国[がいこく], 外国人[がいこくじん]',
        exampleTranslation: 'negara asing, orang asing; warga negara asing',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 37,
      },
      {
        id: 'cmio6dpst00159apfbqcn7ugr',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '多',
        kanjiMeaning: 'sering; banyak; banyak sekali',
        onyomi: 'タ',
        kunyomi: 'おお・い',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '多[おお]い',
        exampleTranslation: 'banyak',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 38,
      },
      {
        id: 'cmio6dpst00169apfu2jr4sqs',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '大',
        kanjiMeaning: 'besar; luas',
        onyomi: 'タイ、ダイ',
        kunyomi: 'おお・きい',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence:
          '大丈夫[だいじょうぶ], 大使館[たいしかん], 大切[たいせつ], 大勢[おおぜい], 大学[だいがく]',
        exampleTranslation:
          'aman; baik-baik saja; OK, kedutaan besar, penting; perlu, banyak orang, universitas; perguruan tinggi',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 39,
      },
      {
        id: 'cmio6dpst00179apfkuk6yy34',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '天',
        kanjiMeaning: 'langit; kekaisaran; angkasa',
        onyomi: 'テン',
        kunyomi: 'あめ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '天気[てんき]',
        exampleTranslation: 'cuaca',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 40,
      },
      {
        id: 'cmio6dpst00189apfpis4joco',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '女',
        kanjiMeaning: 'perempuan; wanita',
        onyomi: 'ジョ',
        kunyomi: 'おんな',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '女[おんな]の子[こ]',
        exampleTranslation: 'gadis; wanita muda',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 41,
      },
      {
        id: 'cmio6dpst00199apfe4ca48wh',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '子',
        kanjiMeaning: 'anak',
        onyomi: 'シ、ス',
        kunyomi: 'こ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '子供[こども], 帽子[ぼうし], 男[おとこ]の子[こ]',
        exampleTranslation: 'anak; anak-anak, topi, anak laki-laki',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 42,
      },
      {
        id: 'cmio6dpst001a9apf3clla9gz',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '学',
        kanjiMeaning: 'pembelajaran; ilmu pengetahuan; belajar',
        onyomi: 'ガク',
        kunyomi: 'まな・ぶ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '学校[がっこう], 留学生[りゅうがくせい]',
        exampleTranslation: 'sekolah, siswa pertukaran',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 43,
      },
      {
        id: 'cmio6dpst001b9apfsfdxsuyf',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '安',
        kanjiMeaning: 'murah; puas; rendah; damai; tenang; santai; beristirahat',
        onyomi: 'アン',
        kunyomi: 'やす・い',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '安[やす]い',
        exampleTranslation: 'murah; tidak mahal',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 44,
      },
      {
        id: 'cmio6dpst001c9apfyjg61u4h',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '小',
        kanjiMeaning: 'kecil; mungil',
        onyomi: 'ショウ',
        kunyomi: 'ちい・さい',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '小[ちい]さい, 小[ちい]さな',
        exampleTranslation: 'kecil; mungil; kecil sekali',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 45,
      },
      {
        id: 'cmio6dpst001d9apfppw23gap',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '少',
        kanjiMeaning: 'sedikit; beberapa',
        onyomi: 'ショウ',
        kunyomi: 'すく・ない、すこ・し',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '少[すく]ない, 少[すこ]し',
        exampleTranslation: 'sedikit; sedikit sekali, jumlah kecil; sedikit; beberapa',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 46,
      },
      {
        id: 'cmio6dpst001e9apfq7fg90yh',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '山',
        kanjiMeaning: 'gunung',
        onyomi: 'サン',
        kunyomi: 'やま',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '沢山[たくさん]',
        exampleTranslation: 'banyak; banyak sekali; sejumlah besar',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 47,
      },
      {
        id: 'cmio6dpst001f9apfj674sgd3',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '川',
        kanjiMeaning: 'sungai',
        onyomi: 'セン',
        kunyomi: 'かわ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '川[かわ]',
        exampleTranslation: 'sungai',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 48,
      },
      {
        id: 'cmio6dpst001g9apfi3glb7of',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '左',
        kanjiMeaning: 'kiri',
        onyomi: 'サ、シャ',
        kunyomi: 'ひだり',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '左[ひだり]',
        exampleTranslation: 'kiri',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 49,
      },
      {
        id: 'cmio6dpst001h9apfrmn64iqs',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '年',
        kanjiMeaning: 'tahun',
        onyomi: 'ネン',
        kunyomi: 'とし',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '年[ねん], 今年[ことし], 再来年[さらいねん], 毎年[まいとし], ～年[ねん]',
        exampleTranslation:
          'tahun, tahun ini, lusa (tahun), setiap tahun; tahunan, tahun (satuan waktu) | penghitung untuk tahun',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 50,
      },
      {
        id: 'cmio6dpst001i9apfqfu4aue5',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '店',
        kanjiMeaning: 'toko; kedai',
        onyomi: 'テン',
        kunyomi: 'みせ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '喫茶店[きっさてん]',
        exampleTranslation: 'kedai kopi; kafe',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 51,
      },
      {
        id: 'cmio6dpst001j9apfrg8p338p',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '後',
        kanjiMeaning: 'belakang; di belakang; kemudian',
        onyomi: 'コウ、ゴ',
        kunyomi: 'あと、うし・ろ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '後[うし]ろ, 午後[ごご]',
        exampleTranslation: 'belakang; di belakang; bagian belakang, siang; p.m.',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 52,
      },
      {
        id: 'cmio6dpst001k9apfm7ulqgs7',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '手',
        kanjiMeaning: 'tangan',
        onyomi: 'シュ、ズ',
        kunyomi: 'て、た',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence:
          '手[て], 上手[じょうず], 下手[へた], 切手[きって], 手紙[てがみ], お手洗[てあら]い',
        exampleTranslation:
          'tangan, terampil; mahir; pandai (dalam), tidak terampil; buruk; canggung, prangko (pos), surat, toilet; kamar kecil',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 53,
      },
      {
        id: 'cmio6dpst001l9apfpsjqqjz5',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '新',
        kanjiMeaning: 'baru',
        onyomi: 'シン',
        kunyomi: 'あたら・しい、あら・た',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '新[あたら]しい, 新聞[しんぶん]',
        exampleTranslation: 'baru, koran',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 54,
      },
      {
        id: 'cmio6dpst001m9apfo1mk5yl0',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '日',
        kanjiMeaning: 'penghitung untuk hari; hari; Jepang; matahari',
        onyomi: 'ジツ、ニチ',
        kunyomi: 'か、び、ひ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence:
          '日[ひ], 七日[なのか], 土曜日[どようび], 日曜日[にちようび], 毎日[まいにち], 誕生[たんじょう]日[び]',
        exampleTranslation:
          'hari, hari ketujuh dalam sebulan, Sabtu, Minggu, setiap hari, ulang tahun',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 55,
      },
      {
        id: 'cmio6dpst001n9apfji6uk8pv',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '時',
        kanjiMeaning: 'jam; waktu',
        onyomi: 'ジ',
        kunyomi: 'どき、とき',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '時々[ときどき], ～時間[じかん], 時間[じかん]',
        exampleTranslation: 'kadang-kadang, periode jam, waktu',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 56,
      },
      {
        id: 'cmio6dpst001o9apfbk90dvqf',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '書',
        kanjiMeaning: 'menulis',
        onyomi: 'ショ',
        kunyomi: 'か・く',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '葉書[はがき], 図書館[としょかん], 辞書[じしょ]',
        exampleTranslation: 'kartu pos, perpustakaan, kamus',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 57,
      },
      {
        id: 'cmio6dpst001p9apfp0l4iudi',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '月',
        kanjiMeaning: 'bulan; bulan (waktu)',
        onyomi: 'ガツ、ゲツ',
        kunyomi: 'つき',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence:
          '月[つき], 一月[いちがつ], 今月[こんげつ], 先月[せんげつ], 月曜日[げつようび], 毎月[まいつき], 来月[らいげつ]',
        exampleTranslation:
          'bulan, Januari, bulan ini, bulan lalu, Senin, setiap bulan, bulan depan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 58,
      },
      {
        id: 'cmio6dpst001q9apfob7vqimd',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '木',
        kanjiMeaning: 'pohon; kayu',
        onyomi: 'ボク、モク',
        kunyomi: 'き',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '木曜日[もくようび]',
        exampleTranslation: 'Kamis',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 59,
      },
      {
        id: 'cmio6dpst001r9apf8gvp055i',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '本',
        kanjiMeaning: 'buku; penghitung untuk benda silindris panjang; asal; nyata; benar',
        onyomi: 'ホン',
        kunyomi: 'もと',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '本当[ほんとう], 本棚[ほんだな], ～本[ほん]',
        exampleTranslation:
          'kebenaran; kenyataan; aktualitas, rak buku, penghitung untuk objek silindris',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 60,
      },
      {
        id: 'cmio6dpst001s9apfk3qv3qo6',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '来',
        kanjiMeaning: 'menjadi; menyebabkan; datang; karena; berikutnya',
        onyomi: 'ライ',
        kunyomi: 'く・る',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '来[く]る, 来月[らいげつ], 来週[らいしゅう]',
        exampleTranslation: 'datang; mendekati, bulan depan, minggu depan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 61,
      },
      {
        id: 'cmio6dpst001t9apfn5vkucr6',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '東',
        kanjiMeaning: 'timur',
        onyomi: 'トウ',
        kunyomi: 'ひがし',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '東[ひがし]',
        exampleTranslation: 'timur',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 62,
      },
      {
        id: 'cmio6dpst001u9apfmv5ue67o',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '校',
        kanjiMeaning: 'koreksi; ujian; percetakan; bukti; sekolah',
        onyomi: 'コウ',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '学校[がっこう]',
        exampleTranslation: 'sekolah',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 63,
      },
      {
        id: 'cmio6dpst001v9apfr3oor9yg',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '母',
        kanjiMeaning: 'ibu',
        onyomi: 'ボ',
        kunyomi: 'はは',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: 'お母[かあ]さん',
        exampleTranslation: 'ibu',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 64,
      },
      {
        id: 'cmio6dpst001w9apfb3dh9n21',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '毎',
        kanjiMeaning: 'setiap',
        onyomi: 'マイ',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence:
          '毎年[まいとし], 毎日[まいにち], 毎晩[まいばん], 毎週[まいしゅう], 毎月[まいつき]',
        exampleTranslation:
          'setiap tahun; tahunan, setiap hari, setiap malam, setiap minggu, setiap bulan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 65,
      },
      {
        id: 'cmio6dpst001x9apfufgbppiv',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '気',
        kanjiMeaning: 'udara; atmosfer; pikiran; suasana hati; semangat',
        onyomi: 'キ、ケ',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '元気[げんき], 天気[てんき], 病気[びょうき]',
        exampleTranslation: 'sehat; baik; ceria, cuaca, penyakit; sakit',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 66,
      },
      {
        id: 'cmio6dpsu001y9apfc80tyxq9',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '水',
        kanjiMeaning: 'air',
        onyomi: 'スイ',
        kunyomi: 'みず',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '水曜日[すいようび]',
        exampleTranslation: 'Rabu',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 67,
      },
      {
        id: 'cmio6dpsu001z9apfmabhq0af',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '火',
        kanjiMeaning: 'api',
        onyomi: 'カ',
        kunyomi: 'ひ、び',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '火曜日[かようび]',
        exampleTranslation: 'Selasa',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 68,
      },
      {
        id: 'cmio6dpsu00209apfx27el9fl',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '父',
        kanjiMeaning: 'ayah',
        onyomi: 'フ',
        kunyomi: 'ちち',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: 'お父[とう]さん',
        exampleTranslation: 'ayah',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 69,
      },
      {
        id: 'cmio6dpsu00219apf8bweg3bn',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '生',
        kanjiMeaning: 'kelahiran; asli; kehidupan',
        onyomi: 'ショウ、セイ',
        kunyomi: 'うま・れる、う・む、い・かす、い・きる、い・ける、なま',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '生[う]まれる, 生徒[せいと], 留学生[りゅうがくせい]',
        exampleTranslation: 'dilahirkan, siswa, siswa pertukaran',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 70,
      },
      {
        id: 'cmio6dpsu00229apfonk3cm1i',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '男',
        kanjiMeaning: 'digunakan',
        onyomi: 'ダン',
        kunyomi: 'おとこ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '男[おとこ]の子[こ]',
        exampleTranslation: 'anak laki-laki',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 71,
      },
      {
        id: 'cmio6dpsu00239apfbganxijx',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '白',
        kanjiMeaning: 'putih',
        onyomi: 'ハク',
        kunyomi: 'しろ・い',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '白[しろ]い, 面白[おもしろ]い',
        exampleTranslation: 'putih, menarik; mempesona',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 72,
      },
      {
        id: 'cmio6dpsu00249apfjmr6mwj2',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '百',
        kanjiMeaning: 'seratus',
        onyomi: 'ヒャク、ビャク',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '百[ひゃく]',
        exampleTranslation: 'seratus',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 73,
      },
      {
        id: 'cmio6dpsu00259apfq6arf5bg',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '目',
        kanjiMeaning: 'mata; bantuan; wawasan; melihat',
        onyomi: 'モク',
        kunyomi: 'め',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '目[め]',
        exampleTranslation: 'mata',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 74,
      },
      {
        id: 'cmio6dpsu00269apffrlq2few',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '社',
        kanjiMeaning: 'asosiasi; perusahaan; firma',
        onyomi: 'シャ',
        kunyomi: 'やしろ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '会社[かいしゃ]',
        exampleTranslation: 'perusahaan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 75,
      },
      {
        id: 'cmio6dpsu00279apfqjq2sr0z',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '空',
        kanjiMeaning: 'kosong; langit; lowong; vakum; hampa',
        onyomi: 'クウ',
        kunyomi: 'そら、あ・く、あ・ける',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '空[そら]',
        exampleTranslation: 'langit',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 76,
      },
      {
        id: 'cmio6dpsu00289apfkmmeeyno',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '立',
        kanjiMeaning: 'berdiri; tegak; bangkit; mendirikan',
        onyomi: 'リツ',
        kunyomi: 'た・つ、た・てる',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '立[た]つ, 立派[りっぱ]',
        exampleTranslation: 'berdiri; bangkit, luar biasa; bagus',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 77,
      },
      {
        id: 'cmio6dpsu00299apfpycifjjb',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '耳',
        kanjiMeaning: 'telinga',
        onyomi: 'ジ',
        kunyomi: 'みみ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '耳[みみ]',
        exampleTranslation: 'telinga',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 78,
      },
      {
        id: 'cmio6dpsu002a9apf7sgp262j',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '聞',
        kanjiMeaning: 'bertanya; mendengar; mendengarkan',
        onyomi: 'ブン',
        kunyomi: 'き・く',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '聞[き]く',
        exampleTranslation: 'mendengar; mendengarkan | bertanya',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 79,
      },
      {
        id: 'cmio6dpsu002b9apfh8diptdj',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '花',
        kanjiMeaning: 'bunga',
        onyomi: 'カ',
        kunyomi: 'はな',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '花瓶[かびん]',
        exampleTranslation: 'vas (bunga)',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 80,
      },
      {
        id: 'cmio6dpsu002c9apf68jk0973',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '行',
        kanjiMeaning: 'pergi; bertindak; melaksanakan; baris; deretan',
        onyomi: 'ギョウ、コウ',
        kunyomi: 'い・く、おこな・う、ゆ・く',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '行[い]く, 旅行[りょこう], 銀行[ぎんこう], 飛行機[ひこうき]',
        exampleTranslation: 'pergi; menuju (ke arah), perjalanan, bank, pesawat terbang',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 81,
      },
      {
        id: 'cmio6dpsu002d9apf4qwhhyf9',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '西',
        kanjiMeaning: 'barat',
        onyomi: 'サイ、セイ',
        kunyomi: 'にし',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '西[にし]',
        exampleTranslation: 'barat',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 82,
      },
      {
        id: 'cmio6dpsu002e9apfn1qvd996',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '見',
        kanjiMeaning: 'melihat; pendapat; lihat; terlihat',
        onyomi: 'ケン',
        kunyomi: 'み・る、み・せる',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '見[み]せる, 見[み]る',
        exampleTranslation: 'menunjukkan; memperlihatkan, melihat; memandang',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 83,
      },
      {
        id: 'cmio6dpsu002f9apfnk0i6dwz',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '言',
        kanjiMeaning: 'mengatakan; kata',
        onyomi: 'ゲン、ゴン',
        kunyomi: 'い・う、こと',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '言[い]う, 言葉[ことば]',
        exampleTranslation: 'mengatakan; mengucapkan, kata; frasa',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 84,
      },
      {
        id: 'cmio6dpsu002g9apf2qyply37',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '話',
        kanjiMeaning: 'cerita; berbicara',
        onyomi: 'ワ',
        kunyomi: 'はなし、はな・す',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '話[はな]す, 電話[でんわ]',
        exampleTranslation:
          'berbicara; bercakap-cakap; bertutur, panggilan telepon | telepon (perangkat)',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 85,
      },
      {
        id: 'cmio6dpsu002h9apfwuhd9lc6',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '語',
        kanjiMeaning: 'bahasa; pidato; kata',
        onyomi: 'ゴ',
        kunyomi: 'かた・る',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '英語[えいご]',
        exampleTranslation: 'bahasa Inggris',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 86,
      },
      {
        id: 'cmio6dpsu002i9apfbf7vn1h0',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '読',
        kanjiMeaning: 'membaca',
        onyomi: 'ドク',
        kunyomi: 'よ・む',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '読[よ]む',
        exampleTranslation: 'membaca',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 87,
      },
      {
        id: 'cmio6dpsu002j9apf8jw7yrlp',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '買',
        kanjiMeaning: 'membeli',
        onyomi: 'バイ',
        kunyomi: 'か・う',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '買[か]う, 買[か]い物[もの]',
        exampleTranslation: 'membeli, berbelanja; barang yang dibeli',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 88,
      },
      {
        id: 'cmio6dpsu002k9apfpwgnt9bm',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '足',
        kanjiMeaning: 'kaki; cukup; penghitung untuk pasang alas kaki; kaki; tungkai',
        onyomi: 'ソク',
        kunyomi: 'あし、た・す、た・りる',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '足[あし]',
        exampleTranslation: 'kaki',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 89,
      },
      {
        id: 'cmio6dpsu002l9apfzams6x8x',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '車',
        kanjiMeaning: 'mobil',
        onyomi: 'シャ',
        kunyomi: 'くるま',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '車[くるま], 自動車[じどうしゃ], 自転車[じてんしゃ], 電車[でんしゃ]',
        exampleTranslation: 'mobil; kendaraan, mobil, sepeda, kereta',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 90,
      },
      {
        id: 'cmio6dpsu002m9apfax67nnjb',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '週',
        kanjiMeaning: 'minggu',
        onyomi: 'シュウ',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence:
          '週[しゅう], 今週[こんしゅう], 先週[せんしゅう], 来週[らいしゅう], 毎週[まいしゅう], ～週間[しゅうかん]',
        exampleTranslation:
          'minggu, minggu ini, minggu lalu, minggu depan, setiap minggu, periode minggu',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 91,
      },
      {
        id: 'cmio6dpsu002n9apfadkinami',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '道',
        kanjiMeaning: 'kursus; distrik; perjalanan; moral; jalan raya; jalan; ajaran',
        onyomi: 'トウ、ドウ',
        kunyomi: 'みち',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '道[みち]',
        exampleTranslation: 'jalan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 92,
      },
      {
        id: 'cmio6dpsu002o9apf91lq6mnx',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '金',
        kanjiMeaning: 'emas',
        onyomi: 'キン',
        kunyomi: 'かね',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '金曜日[きんようび]',
        exampleTranslation: 'Jumat',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 93,
      },
      {
        id: 'cmio6dpsu002p9apf6wzryt8q',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '長',
        kanjiMeaning: 'pemimpin; panjang; senior; superior',
        onyomi: 'チョウ',
        kunyomi: 'なが・い',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '長[なが]い',
        exampleTranslation: 'panjang (jarak atau waktu)',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 94,
      },
      {
        id: 'cmio6dpsu002q9apfs1261tts',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '間',
        kanjiMeaning: 'interval; ruang',
        onyomi: 'カン、ケン',
        kunyomi: 'あいだ、ま',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '時間[じかん]',
        exampleTranslation: 'waktu',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 95,
      },
      {
        id: 'cmio6dpsu002r9apfqkg7un31',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '雨',
        kanjiMeaning: 'hujan',
        onyomi: 'ウ',
        kunyomi: 'あめ',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '雨[あめ], 雨季[うき]',
        exampleTranslation: 'hujan; musim hujan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 96,
      },
      {
        id: 'cmio6dpsu002s9apf9f0l66lz',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '電',
        kanjiMeaning: 'listrik',
        onyomi: 'デン',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '電気[でんき]ストーブ, 電話[でんわ], 電車[でんしゃ]',
        exampleTranslation: 'pemanas listrik, panggilan telepon | telepon (perangkat), kereta',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 97,
      },
      {
        id: 'cmio6dpsu002t9apf941r7msy',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '食',
        kanjiMeaning: 'makan; makanan',
        onyomi: 'ショク',
        kunyomi: 'た・べる、く・う',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '食[た]べる, 食[た]べ物[もの], 食堂[しょくどう]',
        exampleTranslation: 'makan, makanan, kantin',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 98,
      },
      {
        id: 'cmio6dpsu002u9apf6dgeb01q',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '飲',
        kanjiMeaning: 'minum; merokok; mengambil',
        onyomi: 'イン',
        kunyomi: 'の・む',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '飲[の]む, 飲[の]み物[もの]',
        exampleTranslation: 'minum; menelan; minum (obat), minuman',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 99,
      },
      {
        id: 'cmio6dpsu002v9apfewclteqp',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '駅',
        kanjiMeaning: 'stasiun',
        onyomi: 'エキ',
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '駅[えき]',
        exampleTranslation: 'stasiun kereta',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 100,
      },
      {
        id: 'cmio6dpsv002w9apfmcgn68bu',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '高',
        kanjiMeaning: 'mahal; tinggi; jangkung',
        onyomi: 'コウ',
        kunyomi: 'たか・い、たか・まる、たか・める',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '高[たか]い, 高校[こうこう]',
        exampleTranslation: 'tinggi; jangkung | mahal, sekolah menengah atas',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 101,
      },
      {
        id: 'cmio6dpsv002x9apfu1psgb5h',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '魚',
        kanjiMeaning: 'ikan',
        onyomi: 'ギョ',
        kunyomi: 'さかな',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: '魚[さかな]',
        exampleTranslation: 'ikan',
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 102,
      },
    ],
  },
  {
    id: 'cmirg3kc40035135xzwlblxio',
    name: 'Random',
    description: null,
    category: 'Mixed',
    difficulty: 'N5',
    isPublic: true,
    totalCards: 2,
    creatorEmail: 'ajib18j@gmail.com',
    flashcards: [
      {
        id: 'cmirg535v0038135xrdod6ob7',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '祭',
        kanjiMeaning: 'ritual, offer prayers, celebrate, deify, enshrine',
        onyomi: null,
        kunyomi: null,
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: null,
        exampleTranslation: null,
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 0,
      },
      {
        id: 'cmirgau6b003g135x6njqnfhx',
        cardType: 'kanji',
        character: null,
        romaji: null,
        strokeSvg: null,
        kanji: '葵',
        kanjiMeaning: 'hollyhock',
        onyomi: 'キ',
        kunyomi: 'あおい',
        word: null,
        wordMeaning: null,
        reading: null,
        partOfSpeech: null,
        grammarPoint: null,
        grammarMeaning: null,
        usageNote: null,
        exampleSentence: null,
        exampleTranslation: null,
        notes: null,
        tags: null,
        audioUrl: null,
        exampleAudioUrl: null,
        position: 1,
      },
    ],
  },
];

export async function seedDecks() {
  console.log('Seeding public/system decks...');

  // Find admin user for deck ownership
  const adminUser = await prisma.user.findFirst({
    where: { isAdmin: true },
  });

  if (!adminUser) {
    console.log('⚠️ No admin user found. Please create an admin first.');
    return;
  }

  for (const deckData of decksData) {
    const { flashcards, creatorEmail, ...deck } = deckData;

    // Find creator or use admin
    let creator = await prisma.user.findUnique({
      where: { email: creatorEmail },
    });

    if (!creator) {
      creator = adminUser;
    }

    const created = await prisma.deck.upsert({
      where: { id: deck.id },
      update: {
        name: deck.name,
        description: deck.description,
        category: deck.category,
        difficulty: deck.difficulty,
        isPublic: deck.isPublic,
        totalCards: deck.totalCards,
        isActive: true,
      },
      create: {
        id: deck.id,
        name: deck.name,
        description: deck.description,
        category: deck.category,
        difficulty: deck.difficulty,
        isPublic: deck.isPublic,
        totalCards: deck.totalCards,
        createdBy: creator.id,
        isActive: true,
      },
    });

    // Create flashcards
    for (const fc of flashcards) {
      await prisma.flashcard.upsert({
        where: { id: fc.id },
        update: {
          deckId: created.id,
          cardType: fc.cardType,
          character: fc.character,
          romaji: fc.romaji,
          strokeSvg: fc.strokeSvg,
          kanji: fc.kanji,
          kanjiMeaning: fc.kanjiMeaning,
          onyomi: fc.onyomi,
          kunyomi: fc.kunyomi,
          word: fc.word,
          wordMeaning: fc.wordMeaning,
          reading: fc.reading,
          partOfSpeech: fc.partOfSpeech,
          grammarPoint: fc.grammarPoint,
          grammarMeaning: fc.grammarMeaning,
          usageNote: fc.usageNote,
          exampleSentence: fc.exampleSentence,
          exampleTranslation: fc.exampleTranslation,
          notes: fc.notes,
          tags: fc.tags === null ? Prisma.JsonNull : fc.tags,
          audioUrl: fc.audioUrl,
          exampleAudioUrl: fc.exampleAudioUrl,
          position: fc.position,
          isActive: true,
        },
        create: {
          id: fc.id,
          deckId: created.id,
          cardType: fc.cardType,
          character: fc.character,
          romaji: fc.romaji,
          strokeSvg: fc.strokeSvg,
          kanji: fc.kanji,
          kanjiMeaning: fc.kanjiMeaning,
          onyomi: fc.onyomi,
          kunyomi: fc.kunyomi,
          word: fc.word,
          wordMeaning: fc.wordMeaning,
          reading: fc.reading,
          partOfSpeech: fc.partOfSpeech,
          grammarPoint: fc.grammarPoint,
          grammarMeaning: fc.grammarMeaning,
          usageNote: fc.usageNote,
          exampleSentence: fc.exampleSentence,
          exampleTranslation: fc.exampleTranslation,
          notes: fc.notes,
          tags: fc.tags === null ? Prisma.JsonNull : fc.tags,
          audioUrl: fc.audioUrl,
          exampleAudioUrl: fc.exampleAudioUrl,
          position: fc.position,
          isActive: true,
        },
      });
    }

    console.log(`✓ Deck: ${created.name} (${flashcards.length} cards)`);
  }

  console.log(`✅ ${decksData.length} decks seeded successfully!`);
}

// Run if executed directly
if (require.main === module) {
  seedDecks()
    .catch(e => {
      console.error(e);
      process.exit(1);
    })
    .finally(() => prisma.$disconnect());
}
