/**
 * JLPT Mondai Configuration
 * Defines the structure and requirements for each mondai type across all levels
 */

export type MondaiType =
  | 'standard'
  | 'short_reading'
  | 'medium_reading'
  | 'long_reading'
  | 'cloze_test'
  | 'ab_comparison';

export interface MondaiConfig {
  level: string;
  section: string;
  mondai: number;
  name: string;
  description: string;
  questionNumbers: number[];
  requiresPassage: boolean;
  passageCount?: number; // Number of passages required
  questionsPerPassage?: number; // Questions per passage
  mondaiType: MondaiType;
  passageType?: 'text' | 'audio' | 'image';
}

export const MONDAI_CONFIGURATIONS: Record<string, MondaiConfig> = {
  // ===== N5 =====
  'N5-vocabulary-1': {
    level: 'N5',
    section: 'vocabulary',
    mondai: 1,
    name: '漢字読み',
    description: 'Kanji reading questions',
    questionNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N5-vocabulary-2': {
    level: 'N5',
    section: 'vocabulary',
    mondai: 2,
    name: '表記',
    description: 'Orthography questions',
    questionNumbers: [13, 14, 15, 16, 17, 18, 19, 20],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N5-vocabulary-3': {
    level: 'N5',
    section: 'vocabulary',
    mondai: 3,
    name: '文脈規定',
    description: 'Contextually-defined expressions',
    questionNumbers: [21, 22, 23, 24, 25],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N5-vocabulary-4': {
    level: 'N5',
    section: 'vocabulary',
    mondai: 4,
    name: '言い換え類義',
    description: 'Paraphrases',
    questionNumbers: [26, 27, 28, 29, 30],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N5-grammar_reading-1': {
    level: 'N5',
    section: 'grammar_reading',
    mondai: 1,
    name: '文法形式の判断',
    description: 'Sentence grammar',
    questionNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N5-grammar_reading-2': {
    level: 'N5',
    section: 'grammar_reading',
    mondai: 2,
    name: '文の組み立て',
    description: 'Sentence composition',
    questionNumbers: [17, 18, 19, 20, 21],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N5-grammar_reading-3': {
    level: 'N5',
    section: 'grammar_reading',
    mondai: 3,
    name: '文章の文法',
    description: 'Text grammar',
    questionNumbers: [22, 23, 24, 25, 26],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N5-grammar_reading-4': {
    level: 'N5',
    section: 'grammar_reading',
    mondai: 4,
    name: '内容理解（短文）',
    description: 'Short text comprehension',
    questionNumbers: [27, 28, 29],
    requiresPassage: true,
    passageCount: 3,
    questionsPerPassage: 1,
    mondaiType: 'short_reading',
    passageType: 'text',
  },
  'N5-grammar_reading-5': {
    level: 'N5',
    section: 'grammar_reading',
    mondai: 5,
    name: '内容理解（中文）',
    description: 'Medium text comprehension',
    questionNumbers: [30, 31],
    requiresPassage: true,
    passageCount: 2,
    questionsPerPassage: 1,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },
  'N5-grammar_reading-6': {
    level: 'N5',
    section: 'grammar_reading',
    mondai: 6,
    name: '情報検索',
    description: 'Information retrieval',
    questionNumbers: [32],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 1,
    mondaiType: 'short_reading',
    passageType: 'text',
  },

  // ===== N4 =====
  'N4-vocabulary-1': {
    level: 'N4',
    section: 'vocabulary',
    mondai: 1,
    name: '漢字読み',
    description: 'Kanji reading',
    questionNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N4-vocabulary-2': {
    level: 'N4',
    section: 'vocabulary',
    mondai: 2,
    name: '表記',
    description: 'Orthography',
    questionNumbers: [10, 11, 12, 13, 14, 15],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N4-vocabulary-3': {
    level: 'N4',
    section: 'vocabulary',
    mondai: 3,
    name: '文脈規定',
    description: 'Contextually-defined expressions',
    questionNumbers: [16, 17, 18, 19, 20],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N4-vocabulary-4': {
    level: 'N4',
    section: 'vocabulary',
    mondai: 4,
    name: '言い換え類義',
    description: 'Paraphrases',
    questionNumbers: [21, 22, 23, 24, 25],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N4-vocabulary-5': {
    level: 'N4',
    section: 'vocabulary',
    mondai: 5,
    name: '用法',
    description: 'Usage',
    questionNumbers: [26, 27, 28, 29, 30],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N4-grammar_reading-1': {
    level: 'N4',
    section: 'grammar_reading',
    mondai: 1,
    name: '文法形式の判断',
    description: 'Sentence grammar',
    questionNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N4-grammar_reading-2': {
    level: 'N4',
    section: 'grammar_reading',
    mondai: 2,
    name: '文の組み立て',
    description: 'Sentence composition',
    questionNumbers: [16, 17, 18, 19, 20],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N4-grammar_reading-3': {
    level: 'N4',
    section: 'grammar_reading',
    mondai: 3,
    name: '文章の文法',
    description: 'Text grammar',
    questionNumbers: [21, 22, 23, 24, 25],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N4-grammar_reading-4': {
    level: 'N4',
    section: 'grammar_reading',
    mondai: 4,
    name: '内容理解（短文）',
    description: 'Short text comprehension',
    questionNumbers: [26, 27, 28, 29],
    requiresPassage: true,
    passageCount: 4,
    questionsPerPassage: 1,
    mondaiType: 'short_reading',
    passageType: 'text',
  },
  'N4-grammar_reading-5': {
    level: 'N4',
    section: 'grammar_reading',
    mondai: 5,
    name: '内容理解（中文）',
    description: 'Medium text comprehension',
    questionNumbers: [30, 31, 32],
    requiresPassage: true,
    passageCount: 3,
    questionsPerPassage: 1,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },
  'N4-grammar_reading-6': {
    level: 'N4',
    section: 'grammar_reading',
    mondai: 6,
    name: '情報検索',
    description: 'Information retrieval',
    questionNumbers: [33, 34, 35],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 3,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },

  // ===== N3 =====
  'N3-vocabulary-1': {
    level: 'N3',
    section: 'vocabulary',
    mondai: 1,
    name: '漢字読み',
    description: 'Kanji reading',
    questionNumbers: [1, 2, 3, 4, 5, 6, 7, 8],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N3-vocabulary-2': {
    level: 'N3',
    section: 'vocabulary',
    mondai: 2,
    name: '表記',
    description: 'Orthography',
    questionNumbers: [9, 10, 11, 12, 13, 14],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N3-vocabulary-3': {
    level: 'N3',
    section: 'vocabulary',
    mondai: 3,
    name: '文脈規定',
    description: 'Contextually-defined expressions',
    questionNumbers: [15, 16, 17, 18, 19],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N3-vocabulary-4': {
    level: 'N3',
    section: 'vocabulary',
    mondai: 4,
    name: '言い換え類義',
    description: 'Paraphrases',
    questionNumbers: [20, 21, 22, 23, 24],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N3-vocabulary-5': {
    level: 'N3',
    section: 'vocabulary',
    mondai: 5,
    name: '用法',
    description: 'Usage',
    questionNumbers: [25, 26, 27, 28, 29, 30],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N3-grammar_reading-1': {
    level: 'N3',
    section: 'grammar_reading',
    mondai: 1,
    name: '文法形式の判断',
    description: 'Sentence grammar',
    questionNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N3-grammar_reading-2': {
    level: 'N3',
    section: 'grammar_reading',
    mondai: 2,
    name: '文の組み立て',
    description: 'Sentence composition',
    questionNumbers: [14, 15, 16, 17, 18],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N3-grammar_reading-3': {
    level: 'N3',
    section: 'grammar_reading',
    mondai: 3,
    name: '文章の文法',
    description: 'Text grammar (Cloze Test)',
    questionNumbers: [19, 20, 21, 22, 23],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 5,
    mondaiType: 'cloze_test',
    passageType: 'text',
  },
  'N3-grammar_reading-4': {
    level: 'N3',
    section: 'grammar_reading',
    mondai: 4,
    name: '内容理解（短文）',
    description: 'Short text comprehension',
    questionNumbers: [24, 25, 26, 27, 28, 29],
    requiresPassage: true,
    passageCount: 6,
    questionsPerPassage: 1,
    mondaiType: 'short_reading',
    passageType: 'text',
  },
  'N3-grammar_reading-5': {
    level: 'N3',
    section: 'grammar_reading',
    mondai: 5,
    name: '内容理解（中文）',
    description: 'Medium text comprehension',
    questionNumbers: [30, 31, 32, 33],
    requiresPassage: true,
    passageCount: 4,
    questionsPerPassage: 1,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },
  'N3-grammar_reading-6': {
    level: 'N3',
    section: 'grammar_reading',
    mondai: 6,
    name: '内容理解（長文）',
    description: 'Long text comprehension',
    questionNumbers: [34, 35, 36, 37],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 4,
    mondaiType: 'long_reading',
    passageType: 'text',
  },
  'N3-grammar_reading-7': {
    level: 'N3',
    section: 'grammar_reading',
    mondai: 7,
    name: '情報検索',
    description: 'Information retrieval',
    questionNumbers: [38, 39],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 2,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },

  // ===== N2 =====
  'N2-vocabulary-1': {
    level: 'N2',
    section: 'vocabulary',
    mondai: 1,
    name: '漢字読み',
    description: 'Kanji reading',
    questionNumbers: [1, 2, 3, 4, 5],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N2-vocabulary-2': {
    level: 'N2',
    section: 'vocabulary',
    mondai: 2,
    name: '表記',
    description: 'Orthography',
    questionNumbers: [6, 7, 8, 9, 10],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N2-vocabulary-3': {
    level: 'N2',
    section: 'vocabulary',
    mondai: 3,
    name: '文脈規定',
    description: 'Contextually-defined expressions',
    questionNumbers: [11, 12, 13, 14, 15, 16, 17],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N2-vocabulary-4': {
    level: 'N2',
    section: 'vocabulary',
    mondai: 4,
    name: '言い換え類義',
    description: 'Paraphrases',
    questionNumbers: [18, 19, 20, 21, 22],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N2-vocabulary-5': {
    level: 'N2',
    section: 'vocabulary',
    mondai: 5,
    name: '用法',
    description: 'Usage',
    questionNumbers: [23, 24, 25, 26, 27],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N2-grammar_reading-1': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 1,
    name: '文法形式の判断',
    description: 'Sentence grammar',
    questionNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N2-grammar_reading-2': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 2,
    name: '文の組み立て',
    description: 'Sentence composition',
    questionNumbers: [11, 12, 13, 14, 15],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N2-grammar_reading-3': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 3,
    name: '文章の文法',
    description: 'Text grammar',
    questionNumbers: [16, 17, 18, 19, 20],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N2-grammar_reading-4': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 4,
    name: '内容理解（短文）',
    description: 'Short text comprehension',
    questionNumbers: [21, 22, 23, 24, 25],
    requiresPassage: true,
    passageCount: 5,
    questionsPerPassage: 1,
    mondaiType: 'short_reading',
    passageType: 'text',
  },
  'N2-grammar_reading-5': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 5,
    name: '内容理解（中文）',
    description: 'Medium text comprehension',
    questionNumbers: [26, 27, 28, 29, 30, 31, 32, 33, 34],
    requiresPassage: true,
    passageCount: 9,
    questionsPerPassage: 1,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },
  'N2-grammar_reading-6': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 6,
    name: '統合理解',
    description: 'Integrated comprehension',
    questionNumbers: [35, 36, 37, 38, 39, 40],
    requiresPassage: true,
    passageCount: 2,
    questionsPerPassage: 3,
    mondaiType: 'long_reading',
    passageType: 'text',
  },
  'N2-grammar_reading-7': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 7,
    name: '主張理解（長文）',
    description: 'Long text (opinion)',
    questionNumbers: [41, 42, 43, 44],
    requiresPassage: true,
    passageCount: 4,
    questionsPerPassage: 1,
    mondaiType: 'short_reading',
    passageType: 'text',
  },
  'N2-grammar_reading-8': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 8,
    name: '内容理解（長文）',
    description: 'Long text comprehension',
    questionNumbers: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
    requiresPassage: true,
    passageCount: 5,
    questionsPerPassage: 3,
    mondaiType: 'long_reading',
    passageType: 'text',
  },
  'N2-grammar_reading-9': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 9,
    name: '統合理解',
    description: 'Integrated comprehension',
    questionNumbers: [60, 61, 62, 63, 64, 65, 66, 67, 68],
    requiresPassage: true,
    passageCount: 3,
    questionsPerPassage: 3,
    mondaiType: 'long_reading',
    passageType: 'text',
  },
  'N2-grammar_reading-10': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 10,
    name: '主張理解（長文）',
    description: 'Long text (opinion)',
    questionNumbers: [69, 70, 71],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 3,
    mondaiType: 'ab_comparison',
    passageType: 'text',
  },
  'N2-grammar_reading-11': {
    level: 'N2',
    section: 'grammar_reading',
    mondai: 11,
    name: '情報検索',
    description: 'Information retrieval',
    questionNumbers: [72, 73],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 2,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },

  // ===== N1 =====
  'N1-vocabulary-1': {
    level: 'N1',
    section: 'vocabulary',
    mondai: 1,
    name: '漢字読み',
    description: 'Kanji reading',
    questionNumbers: [1, 2, 3, 4, 5, 6],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N1-vocabulary-2': {
    level: 'N1',
    section: 'vocabulary',
    mondai: 2,
    name: '文脈規定',
    description: 'Contextually-defined expressions',
    questionNumbers: [7, 8, 9, 10, 11, 12, 13],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N1-vocabulary-3': {
    level: 'N1',
    section: 'vocabulary',
    mondai: 3,
    name: '言い換え類義',
    description: 'Paraphrases',
    questionNumbers: [14, 15, 16, 17, 18, 19, 20],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N1-vocabulary-4': {
    level: 'N1',
    section: 'vocabulary',
    mondai: 4,
    name: '用法',
    description: 'Usage',
    questionNumbers: [21, 22, 23, 24, 25],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N1-grammar_reading-1': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 1,
    name: '文法形式の判断',
    description: 'Sentence grammar',
    questionNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N1-grammar_reading-2': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 2,
    name: '文の組み立て',
    description: 'Sentence composition',
    questionNumbers: [11, 12, 13, 14, 15],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N1-grammar_reading-3': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 3,
    name: '文章の文法',
    description: 'Text grammar',
    questionNumbers: [16, 17, 18, 19, 20],
    requiresPassage: false,
    mondaiType: 'standard',
  },
  'N1-grammar_reading-4': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 4,
    name: '内容理解（短文）',
    description: 'Short text comprehension',
    questionNumbers: [21, 22, 23, 24, 25],
    requiresPassage: true,
    passageCount: 5,
    questionsPerPassage: 1,
    mondaiType: 'short_reading',
    passageType: 'text',
  },
  'N1-grammar_reading-5': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 5,
    name: '内容理解（中文）',
    description: 'Medium text comprehension',
    questionNumbers: [26, 27, 28, 29, 30, 31, 32, 33, 34],
    requiresPassage: true,
    passageCount: 9,
    questionsPerPassage: 1,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },
  'N1-grammar_reading-6': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 6,
    name: '統合理解',
    description: 'Integrated comprehension',
    questionNumbers: [35, 36, 37, 38, 39, 40],
    requiresPassage: true,
    passageCount: 2,
    questionsPerPassage: 3,
    mondaiType: 'long_reading',
    passageType: 'text',
  },
  'N1-grammar_reading-7': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 7,
    name: '主張理解（長文）',
    description: 'Long text (opinion)',
    questionNumbers: [41, 42, 43, 44],
    requiresPassage: true,
    passageCount: 4,
    questionsPerPassage: 1,
    mondaiType: 'short_reading',
    passageType: 'text',
  },
  'N1-grammar_reading-8': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 8,
    name: '内容理解（長文）',
    description: 'Long text comprehension',
    questionNumbers: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58],
    requiresPassage: true,
    passageCount: 5,
    questionsPerPassage: 3,
    mondaiType: 'long_reading',
    passageType: 'text',
  },
  'N1-grammar_reading-9': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 9,
    name: '統合理解',
    description: 'Integrated comprehension',
    questionNumbers: [59, 60, 61, 62, 63, 64, 65, 66, 67],
    requiresPassage: true,
    passageCount: 3,
    questionsPerPassage: 3,
    mondaiType: 'long_reading',
    passageType: 'text',
  },
  'N1-grammar_reading-10': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 10,
    name: '主張理解（長文）',
    description: 'Long text (opinion)',
    questionNumbers: [68, 69, 70],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 3,
    mondaiType: 'ab_comparison',
    passageType: 'text',
  },
  'N1-grammar_reading-11': {
    level: 'N1',
    section: 'grammar_reading',
    mondai: 11,
    name: '情報検索',
    description: 'Information retrieval',
    questionNumbers: [71, 72],
    requiresPassage: true,
    passageCount: 1,
    questionsPerPassage: 2,
    mondaiType: 'medium_reading',
    passageType: 'text',
  },
};

/**
 * Get mondai configuration
 */
export function getMondaiConfig(level: string, section: string, mondai: number): MondaiConfig | undefined {
  const key = `${level}-${section}-${mondai}`;
  return MONDAI_CONFIGURATIONS[key];
}

/**
 * Get all mondai for a section
 */
export function getSectionMondais(level: string, section: string): MondaiConfig[] {
  return Object.values(MONDAI_CONFIGURATIONS).filter(
    (config) => config.level === level && config.section === section
  );
}

/**
 * Get question count for a mondai
 */
export function getMondaiQuestionCount(level: string, section: string, mondai: number): number {
  const config = getMondaiConfig(level, section, mondai);
  return config?.questionNumbers.length || 0;
}
